# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9a73b80bdb8839f291a109d8eccf1869e5367b6c0391783e3e7f9df9007e51b068db09bb9112eb3fd6b898a40694221b4c1f48ac50b3d6865a902625c2f9268

test:
  secret_key_base: bd0f84f2d5f28479ea8fbc048d935d126800cc8fd0c51441c33ac97a7826999001bd6f50e12786dbb6c414c84a32a350059a98f3eed8ec3b9c20031002802047

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
